In [1]:
import tensorflow as tf
tf.test.gpu_device_name()

''

In [2]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 13921897728102654829
 xla_global_id: -1]

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pathlib

In [4]:
import tensorflow as tf

In [5]:
cache_dir = './tmp'
dataset_file_name = 'shakespeare.txt'
dataset_file_origin = 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt'

dataset_file_path = tf.keras.utils.get_file(
    fname=dataset_file_name,
    origin=dataset_file_origin,
    cache_dir=pathlib.Path(cache_dir).absolute()
)

print(dataset_file_path)

/tmp\.keras\datasets\shakespeare.txt


In [6]:
text = open(dataset_file_path, mode='r').read()

print('Length of text: {} characters'.format(len(text)))

Length of text: 1115394 characters


In [7]:
print(text[:500])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor


In [8]:
vocab = sorted(set(text))

In [9]:
vocab

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [10]:
len(vocab)

65

In [11]:
for pair in enumerate(vocab):
  print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '$')
(4, '&')
(5, "'")
(6, ',')
(7, '-')
(8, '.')
(9, '3')
(10, ':')
(11, ';')
(12, '?')
(13, 'A')
(14, 'B')
(15, 'C')
(16, 'D')
(17, 'E')
(18, 'F')
(19, 'G')
(20, 'H')
(21, 'I')
(22, 'J')
(23, 'K')
(24, 'L')
(25, 'M')
(26, 'N')
(27, 'O')
(28, 'P')
(29, 'Q')
(30, 'R')
(31, 'S')
(32, 'T')
(33, 'U')
(34, 'V')
(35, 'W')
(36, 'X')
(37, 'Y')
(38, 'Z')
(39, 'a')
(40, 'b')
(41, 'c')
(42, 'd')
(43, 'e')
(44, 'f')
(45, 'g')
(46, 'h')
(47, 'i')
(48, 'j')
(49, 'k')
(50, 'l')
(51, 'm')
(52, 'n')
(53, 'o')
(54, 'p')
(55, 'q')
(56, 'r')
(57, 's')
(58, 't')
(59, 'u')
(60, 'v')
(61, 'w')
(62, 'x')
(63, 'y')
(64, 'z')


In [12]:
char_to_ind = {char:ind for ind,char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [13]:
char_to_ind['h']

46

In [14]:
ind_to_char = np.array(vocab)

In [15]:
ind_to_char[46]

'h'

In [16]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [17]:
encoded_text

array([18, 47, 56, ..., 45,  8,  0])

In [18]:
encoded_text.shape

(1115394,)

In [19]:
sample = text[:500]

In [20]:
sample

"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor"

In [21]:
encoded_text[:500]

array([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43,
       44, 53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39,
       52, 63,  1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1,
       51, 43,  1, 57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31,
       54, 43, 39, 49,  6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56,
       57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39,
       56, 43,  1, 39, 50, 50,  1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56,
       39, 58, 46, 43, 56,  1, 58, 53,  1, 42, 47, 43,  1, 58, 46, 39, 52,
        1, 58, 53,  1, 44, 39, 51, 47, 57, 46, 12,  0,  0, 13, 50, 50, 10,
        0, 30, 43, 57, 53, 50, 60, 43, 42,  8,  1, 56, 43, 57, 53, 50, 60,
       43, 42,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43,
       52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63, 53, 59,  1, 49, 52, 53,
       61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41, 47, 59, 57,  1, 47,
       57,  1, 41, 46, 47

In [22]:
print(text[:500])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor


In [23]:
line = "First Citizen:"
len(line)

14

In [24]:
lines = '''
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.
'''
len(lines)

82

In [25]:
seq_len = 120

In [26]:
total_num_seq = len(text)//(seq_len+1)
total_num_seq

9218

In [27]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
char_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [28]:
for item in char_dataset.take(500):
  print(item.numpy(), ind_to_char[item.numpy()])


18 F
47 i
56 r
57 s
58 t
1  
15 C
47 i
58 t
47 i
64 z
43 e
52 n
10 :
0 

14 B
43 e
44 f
53 o
56 r
43 e
1  
61 w
43 e
1  
54 p
56 r
53 o
41 c
43 e
43 e
42 d
1  
39 a
52 n
63 y
1  
44 f
59 u
56 r
58 t
46 h
43 e
56 r
6 ,
1  
46 h
43 e
39 a
56 r
1  
51 m
43 e
1  
57 s
54 p
43 e
39 a
49 k
8 .
0 

0 

13 A
50 l
50 l
10 :
0 

31 S
54 p
43 e
39 a
49 k
6 ,
1  
57 s
54 p
43 e
39 a
49 k
8 .
0 

0 

18 F
47 i
56 r
57 s
58 t
1  
15 C
47 i
58 t
47 i
64 z
43 e
52 n
10 :
0 

37 Y
53 o
59 u
1  
39 a
56 r
43 e
1  
39 a
50 l
50 l
1  
56 r
43 e
57 s
53 o
50 l
60 v
43 e
42 d
1  
56 r
39 a
58 t
46 h
43 e
56 r
1  
58 t
53 o
1  
42 d
47 i
43 e
1  
58 t
46 h
39 a
52 n
1  
58 t
53 o
1  
44 f
39 a
51 m
47 i
57 s
46 h
12 ?
0 

0 

13 A
50 l
50 l
10 :
0 

30 R
43 e
57 s
53 o
50 l
60 v
43 e
42 d
8 .
1  
56 r
43 e
57 s
53 o
50 l
60 v
43 e
42 d
8 .
0 

0 

18 F
47 i
56 r
57 s
58 t
1  
15 C
47 i
58 t
47 i
64 z
43 e
52 n
10 :
0 

18 F
47 i
56 r
57 s
58 t
6 ,
1  
63 y
53 o
59 u
1  
49 k
52 n
53 o
61 w
1  
15 C
39 a
47 i

In [29]:
sequences = char_dataset.batch(seq_len+1,drop_remainder=True)

In [30]:
def create_seq_targets(seq):
  input_txt = seq[:-1]
  target_txt = seq[1:]
  return input_txt, target_txt

In [31]:
dataset = sequences.map(create_seq_targets)
dataset

<_MapDataset element_spec=(TensorSpec(shape=(120,), dtype=tf.int32, name=None), TensorSpec(shape=(120,), dtype=tf.int32, name=None))>

In [32]:
for input_txt, target_txt in dataset.take(1):
    print(input_txt.numpy())
    print("".join(ind_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print("".join(ind_to_char[target_txt.numpy()]))

[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1 39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39]
First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved ra


[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1 39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58]
irst Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rat


In [33]:
batch_size = 128

In [34]:
buffer_size = 10000

dataset = dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)
list(dataset.as_numpy_iterator())

[(array([[56, 51,  1, ...,  1, 54, 39],
         [39, 44, 44, ..., 44, 39, 60],
         [50, 39, 59, ..., 42,  1, 43],
         ...,
         [53, 59, 56, ..., 21, 44,  1],
         [ 0, 35, 46, ..., 63,  1, 54],
         [42,  1, 58, ..., 39, 58,  1]]),
  array([[51,  1, 39, ..., 54, 39, 57],
         [44, 44, 43, ..., 39, 60, 53],
         [39, 59, 42, ...,  1, 43, 39],
         ...,
         [59, 56,  1, ..., 44,  1, 63],
         [35, 46, 47, ...,  1, 54, 39],
         [ 1, 58, 39, ..., 58,  1, 63]])),
 (array([[43,  1, 51, ...,  0, 41, 43],
         [52, 53, 58, ..., 30, 27, 25],
         [43, 56, 57, ..., 47, 58, 47],
         ...,
         [ 1, 44, 53, ...,  8,  0,  0],
         [ 1, 50, 53, ..., 39, 50, 50],
         [52, 11,  0, ...,  1, 57, 53]]),
  array([[ 1, 51, 39, ..., 41, 43, 56],
         [53, 58,  1, ..., 27, 25, 17],
         [56, 57, 11, ..., 58, 47, 64],
         ...,
         [44, 53, 56, ...,  0,  0, 16],
         [50, 53, 57, ..., 50, 50, 39],
         [11,  0,

In [68]:
len(dataset)

72

In [36]:
# dataset2 = tf.data.Dataset.range(3)
# dataset2 = dataset2.shuffle(10000, reshuffle_each_iteration=True)
# list(dataset2.as_numpy_iterator())

In [37]:
vocab_size = len(vocab)

In [38]:
vocab_size

65

In [39]:
embed_dim = 64

In [40]:
rnn_neurons = 1026

In [41]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [42]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

help(Embedding)

Help on class Embedding in module keras.src.layers.core.embedding:

class Embedding(keras.src.engine.base_layer.Layer)
 |  Embedding(input_dim, output_dim, embeddings_initializer='uniform', embeddings_regularizer=None, activity_regularizer=None, embeddings_constraint=None, mask_zero=False, input_length=None, sparse=False, **kwargs)
 |  
 |  Turns positive integers (indexes) into dense vectors of fixed size.
 |  
 |  e.g. `[[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]`
 |  
 |  This layer can only be used on positive integer inputs of a fixed range. The
 |  `tf.keras.layers.TextVectorization`, `tf.keras.layers.StringLookup`,
 |  and `tf.keras.layers.IntegerLookup` preprocessing layers can help prepare
 |  inputs for an `Embedding` layer.
 |  
 |  This layer accepts `tf.Tensor`, `tf.RaggedTensor` and `tf.SparseTensor`
 |  input.
 |  
 |  Example:
 |  
 |  >>> model = tf.keras.Sequential()
 |  >>> model.add(tf.keras.layers.Embedding(1000, 64, input_length=10))
 |  >>> # The model will take as

In [44]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(Embedding(vocab_size, embed_dim, batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_neurons, return_sequences=True,
                 stateful=True, recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    model.compile('adam',loss=sparse_cat_loss)
    return model

In [45]:
model = create_model(vocab_size=vocab_size,
                    embed_dim=embed_dim,
                    rnn_neurons=rnn_neurons,
                    batch_size=batch_size)

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           4160      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 65)           66755     
                                                                 
Total params: 3432091 (13.09 MB)
Trainable params: 3432091 (13.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [47]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)

In [48]:
example_batch_predictions.shape

TensorShape([128, 120, 65])

In [49]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
print("length: {}".format(len(sampled_indices)))
sampled_indices

length: 120


<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[ 7],
       [55],
       [26],
       [38],
       [25],
       [19],
       [46],
       [26],
       [56],
       [19],
       [31],
       [54],
       [33],
       [55],
       [ 4],
       [58],
       [61],
       [10],
       [40],
       [59],
       [27],
       [ 2],
       [26],
       [54],
       [13],
       [ 8],
       [55],
       [33],
       [21],
       [20],
       [54],
       [ 9],
       [58],
       [60],
       [51],
       [55],
       [ 0],
       [49],
       [20],
       [28],
       [29],
       [14],
       [26],
       [11],
       [ 4],
       [44],
       [ 9],
       [45],
       [27],
       [ 1],
       [62],
       [ 5],
       [30],
       [ 4],
       [63],
       [15],
       [56],
       [49],
       [48],
       [18],
       [39],
       [58],
       [35],
       [32],
       [28],
       [52],
       [ 7],
       [36],
       [31],
       [15],
       [52],
       [17],
       [55],
   

In [50]:
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()
print(len(sampled_indices))

120


In [51]:
sampled_indices

array([ 7, 55, 26, 38, 25, 19, 46, 26, 56, 19, 31, 54, 33, 55,  4, 58, 61,
       10, 40, 59, 27,  2, 26, 54, 13,  8, 55, 33, 21, 20, 54,  9, 58, 60,
       51, 55,  0, 49, 20, 28, 29, 14, 26, 11,  4, 44,  9, 45, 27,  1, 62,
        5, 30,  4, 63, 15, 56, 49, 48, 18, 39, 58, 35, 32, 28, 52,  7, 36,
       31, 15, 52, 17, 55,  7, 55, 12,  6, 11, 55, 46,  4, 45, 56, 17, 38,
       64, 54, 22,  7, 10, 43, 31, 54, 43, 55, 60, 32,  0, 11,  0, 17, 57,
       18,  2, 41,  4, 17, 63, 47, 51, 25,  3, 10, 47,  0, 35, 38, 35, 39,
       47], dtype=int64)

In [62]:
ind_to_char[sampled_indices]

array(['-', 'q', 'N', 'Z', 'M', 'G', 'h', 'N', 'r', 'G', 'S', 'p', 'U',
       'q', '&', 't', 'w', ':', 'b', 'u', 'O', '!', 'N', 'p', 'A', '.',
       'q', 'U', 'I', 'H', 'p', '3', 't', 'v', 'm', 'q', '\n', 'k', 'H',
       'P', 'Q', 'B', 'N', ';', '&', 'f', '3', 'g', 'O', ' ', 'x', "'",
       'R', '&', 'y', 'C', 'r', 'k', 'j', 'F', 'a', 't', 'W', 'T', 'P',
       'n', '-', 'X', 'S', 'C', 'n', 'E', 'q', '-', 'q', '?', ',', ';',
       'q', 'h', '&', 'g', 'r', 'E', 'Z', 'z', 'p', 'J', '-', ':', 'e',
       'S', 'p', 'e', 'q', 'v', 'T', '\n', ';', '\n', 'E', 's', 'F', '!',
       'c', '&', 'E', 'y', 'i', 'm', 'M', '$', ':', 'i', '\n', 'W', 'Z',
       'W', 'a', 'i'], dtype='<U1')

In [56]:
epochs = 3

In [57]:
model.fit(dataset, epochs=epochs)

Epoch 1/3
72/72 [==============================] - 99s 1s/step - loss: 3.0792
Epoch 2/3
72/72 [==============================] - 110s 2s/step - loss: 2.4329
Epoch 3/3
72/72 [==============================] - 111s 2s/step - loss: 2.2423


In [58]:
model.save_weights('shakespeare2.keras')

In [59]:
model = create_model(vocab_size, embed_dim, rnn_neurons, batch_size=1)
model.load_weights('shakespeare2.keras')

In [60]:
model.build(tf.TensorShape([1, None]))

In [61]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 64)             4160      
                                                                 
 gru_1 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_1 (Dense)             (1, None, 65)             66755     
                                                                 
Total params: 3432091 (13.09 MB)
Trainable params: 3432091 (13.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [63]:
def generate_text(model, start_seed, gen_size=500, temp=1.0):
    num_generate = gen_size
    input_eval = [char_to_ind[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval, 0)
    text_generated = []
    temperature = temp
    model.reset_states()
    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions,0)
        predictions = predictions/temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        input_eval=tf.expand_dims([predicted_id],0)
        text_generated.append(ind_to_char[predicted_id])
    return (start_seed+"".join(text_generated))

In [64]:
print(generate_text(model,"JULIET",gen_size=1000))

JULIETh; I'cn well troum I'
Iwle deith, on t oube ther boor p'ollby.

MORHADCULI
AXIA:
Ne hiendene fat unthaings it thow
Anllow ther, thet ba qutemuce,
Ashen to rillees,
And note not me listle for,

aMapr:
Arcotn yours fule meal, come le.

TIOG:
Gaile iy too hut aply Buarele sa thea a kit is thay here som sed atheng, weit noky
Loe cr wall thellldis as atfore the sithe.
For ch yok my vak!
Ma tlouchis? Sich ho mall!
Thes sat oom ancustwin tale iturs?
Med oxwing? Aver at ofprerisg,
Stare to my to cant nsong thet tere,
Cowhing me
Wornt se by'cl chederrer,
Will dout a wis hasthing
Thepen wa is my the yoe cowiln gathere, marvels, I'd wetr Rotlof se wisperou!
Thet shate ba
Eves ferthow:
Thie 'se ot al mind bincuss! wne nomin of oucs to my se ce may you darut R'entiol;
Hert Gote fell chiRcomit; welly, at seal nkan foike.

GUTTES:
EL Pathing hant dorong
atp mefech usneref aspich nonged if sours.

PUDROND:
U'd Vompnes yae suil
To I comwlla
Shou shepofe and trabk shat, atll hinedads of to pagsyof