In [21]:
from sklearn.linear_model import LinearRegression
import numpy as np

m = 3
b = 2
x = np.arange(1, 3)
y = x*m + b

x = x.reshape(-1,1)
y= y.reshape(-1,1)
print(x,y,sep='\n\n')
model = LinearRegression()

model.fit(x,y)
model.predict(np.arange(11, 20).reshape(-1,1))

[[1]
 [2]]

[[5]
 [8]]


array([[35.],
       [38.],
       [41.],
       [44.],
       [47.],
       [50.],
       [53.],
       [56.],
       [59.]])

In [22]:
model.coef_

array([[3.]])

In [23]:
model.intercept_

array([2.])

In [30]:
class Neuron:
    def __init__(self, xtrain, ytrain, learning_rate, epochs):
        self.xtrain = xtrain
        self.ytrain = ytrain
        self.learning_rate = learning_rate
        self.len_train = len(xtrain)
        self.epochs = epochs
        print(xtrain)
        print(self.len_train)
        
    def parameters_initializer(self):
        self.weight = 1
        self.bias = 1
        print("initial weight and bias:",self.weight,self.bias)
        
    def activate(self):
        self.parameters_initializer()
        epoch = 0
        while epoch<self.epochs and self.calculate_cost_function_mse()!=0:
            epoch+=1
            print("Epoch:",self.epochs,end="\n")
            print("revalued weight and bias",self.revalue_parameters(), end="\n----------------------------------\n")
    
    def calculate_cost_function_mse(self):
        cost_function_mse = 0
        for i in range(self.len_train):
            error=(self.ytrain[i][0]-self.calculate_ypred(self.xtrain[i][0]))
            cost_function_mse+=(error**2)
        print("cfe:",cost_function_mse)
        return cost_function_mse
    
    def calculate_partial_derivative_of_cost_function_withrespect_to_weight(self, old_bias):
        pd_cf_wrt_weight = 0
        for i in range(self.len_train):
            pd_cf_wrt_weight+=((-2*self.xtrain[i][0])*(self.ytrain[i][0]-(self.weight*self.xtrain[i][0]+old_bias)))
        print("pd_cf_wrt_weight: ",pd_cf_wrt_weight)
        return pd_cf_wrt_weight
            
    def calculate_partial_derivative_of_cost_function_withrespect_to_bias(self):
        pd_cf_wrt_bias = 0
        for i in range(self.len_train):
            pd_cf_wrt_bias+=(-2*(self.ytrain[i][0]-(self.weight*self.xtrain[i][0]+self.bias)))
        print("pd_cf_wrt_bias: ",pd_cf_wrt_bias)
        return pd_cf_wrt_bias
    
    def revalue_parameters(self):
        old_bias = self.bias
        self.bias = self.bias - (self.learning_rate*self.calculate_partial_derivative_of_cost_function_withrespect_to_bias())
        self.weight = self.weight - (self.learning_rate*self.calculate_partial_derivative_of_cost_function_withrespect_to_weight(old_bias))
        return self.weight, self.bias
    
    def calculate_ypred(self, x):
        y_pred = (self.weight*x+self.bias)
        print("y_pred:", y_pred)
        return y_pred


neuron = Neuron(x,y,0.01,50)
neuron.activate()

[[1]
 [2]]
2
initial weight and bias: 1 1
y_pred: 2
y_pred: 3
cfe: 34
Epoch: 50
pd_cf_wrt_bias:  -16
pd_cf_wrt_weight:  -26
revalued weight and bias (1.26, 1.16)
----------------------------------
y_pred: 2.42
y_pred: 3.6799999999999997
cfe: 25.318800000000003
Epoch: 50
pd_cf_wrt_bias:  -13.8
pd_cf_wrt_weight:  -22.44
revalued weight and bias (1.4844, 1.298)
----------------------------------
y_pred: 2.7824
y_pred: 4.2668
cfe: 18.854532000000003
Epoch: 50
pd_cf_wrt_bias:  -11.9016
pd_cf_wrt_weight:  -19.368000000000002
revalued weight and bias (1.67808, 1.417016)
----------------------------------
y_pred: 3.095096
y_pred: 4.773176
cfe: 14.041052376191999
Epoch: 50
pd_cf_wrt_bias:  -10.263456
pd_cf_wrt_weight:  -16.717104
revalued weight and bias (1.84525104, 1.51965056)
----------------------------------
y_pred: 3.3649016
y_pred: 5.2101526400000004
cfe: 10.456795069781526
Epoch: 50
pd_cf_wrt_bias:  -8.84989152
pd_cf_wrt_weight:  -14.429586239999999
revalued weight and bias (1.989546902